import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './ContextAPI/AuthContext'
import Navbar from '@/components/Nav'
import Footer from '@/components/Footer'
import { Roboto } from 'next/font/google'


const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
           <Navbar />
        <main className=""> {children} </main>
          <Footer />
        </AuthProvider>
        </body>
    </html>
    
  )
}
